### ISSUE TITLE
styled-system throwing TS error

### ISSUE THREAD

**Issue by meugeniatr** [chakra-ui/panda#3368]
### Description

When I upgraded to 1.3.1, I expected to have no regressions but instead many attributes previously exposed in styled-system throw a TS error.

### Link to Reproduction

https://play.panda-css.com/Idv5bS5j7o

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

NextJS

### Panda CSS Version

1.3.1

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

A few examples I've found when upgrading:
`Property 'className' does not exist on type 'FlexProps'
Property 'children' does not exist on type 'FlexProps'
`
