### ISSUE TITLE
Typescript error on latest version update

### ISSUE THREAD

**Issue by omridevk** [chakra-ui/panda#1707]
### Description

When updating from 0.11.0 to 0.18.3

I am getting a lot of TS errors:
node_modules/@pandacss/types/dist/index.d.ts:11:1 - error TS2308: Module './pattern' has already exported a member named 'Primitive'. Consider explicitly re-exporting to resolve the ambiguity.

### Link to Reproduction

just use latest version with node16 module resolution

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

0.18.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @omridevk,

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a StackBlitz reproduction, and I'll re-open

**Comment by omridevk** [comment]
@segunadebayo yes sorry, had a really messy day, will add a stackblitz.
